name: Run .NET Code Analysis

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'
      - 'UT4MasterServer.Web/**'
  push:
    paths-ignore:
      - '*.md'
      - 'OldReferenceCode/**'
      - 'XMPP-ejabberd/**'
      - 'OldReferenceCode/**'
      - 'Files/Engine.ini'
      - 'UT4MasterServer.Web/**'

jobs:
  dotnet-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run .NET Code Analysis
        uses: dotnet/code-analysis@v1
        id: code-analysis
        with:
          solution: UT4MasterServer.sln
          build-breaking: true
          all-categories: all
